//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RES.Commons.Core.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RES.Commons.Core.Resource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Favorites.
        /// </summary>
        public static string AddFavorites {
            get {
                return ResourceManager.GetString("AddFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation System.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Class .
        /// </summary>
        public static string BannerDesciprtionPart1 {
            get {
                return ResourceManager.GetString("BannerDesciprtionPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Development.
        /// </summary>
        public static string BannerDesciprtionPart2 {
            get {
                return ResourceManager.GetString("BannerDesciprtionPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISU.
        /// </summary>
        public static string BannerTitlePart1 {
            get {
                return ResourceManager.GetString("BannerTitlePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corp.
        /// </summary>
        public static string BannerTitlePart2 {
            get {
                return ResourceManager.GetString("BannerTitlePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Alphabetic Ascending.
        /// </summary>
        public static string ByAlphabeticAscending {
            get {
                return ResourceManager.GetString("ByAlphabeticAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Alphabetic Descending.
        /// </summary>
        public static string ByAlphabeticDescending {
            get {
                return ResourceManager.GetString("ByAlphabeticDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Date Ascending.
        /// </summary>
        public static string ByDateAscending {
            get {
                return ResourceManager.GetString("ByDateAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Date Descending.
        /// </summary>
        public static string ByDateDescending {
            get {
                return ResourceManager.GetString("ByDateDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Ranking.
        /// </summary>
        public static string ByRanking {
            get {
                return ResourceManager.GetString("ByRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Contact.
        /// </summary>
        public static string ContactCreate {
            get {
                return ResourceManager.GetString("ContactCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Contact.
        /// </summary>
        public static string ContactDelete {
            get {
                return ResourceManager.GetString("ContactDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Contact.
        /// </summary>
        public static string ContactEdit {
            get {
                return ResourceManager.GetString("ContactEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Contact.
        /// </summary>
        public static string ContactList {
            get {
                return ResourceManager.GetString("ContactList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name .
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Type.
        /// </summary>
        public static string ContactType {
            get {
                return ResourceManager.GetString("ContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BirthDate.
        /// </summary>
        public static string InvalidBirthDate {
            get {
                return ResourceManager.GetString("InvalidBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Contact Name.
        /// </summary>
        public static string InvalidContactName {
            get {
                return ResourceManager.GetString("InvalidContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Phone.
        /// </summary>
        public static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Data Invalid.
        /// </summary>
        public static string MessageContactInvalid {
            get {
                return ResourceManager.GetString("MessageContactInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name Required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name Too Long.
        /// </summary>
        public static string NameTooLong {
            get {
                return ResourceManager.GetString("NameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact not found.
        /// </summary>
        public static string NotFoundContact {
            get {
                return ResourceManager.GetString("NotFoundContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string Ranking {
            get {
                return ResourceManager.GetString("Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Reservation.
        /// </summary>
        public static string ReservationCreate {
            get {
                return ResourceManager.GetString("ReservationCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Reservation.
        /// </summary>
        public static string ReservationDelete {
            get {
                return ResourceManager.GetString("ReservationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Reservation.
        /// </summary>
        public static string ReservationEdit {
            get {
                return ResourceManager.GetString("ReservationEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation List.
        /// </summary>
        public static string ReservationList {
            get {
                return ResourceManager.GetString("ReservationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this contact?.
        /// </summary>
        public static string Term {
            get {
                return ResourceManager.GetString("Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Contact.
        /// </summary>
        public static string TermTitle {
            get {
                return ResourceManager.GetString("TermTitle", resourceCulture);
            }
        }
    }
}
